apiVersion: v1
kind: Namespace
metadata:
  name: linklogsfix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linklogsfix
  namespace: linklogsfix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: linklogsfix
  name: system:openshift:scc:privileged
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: linklogsfix
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: linklogsfix
  namespace: linklogsfix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: linklogsfix
  name: system:openshift:scc:anyuid
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: linklogsfix
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:scc:linklogsfixanyuid
subjects:
- kind: ServiceAccount
  name: linklogsfix
  namespace: linklogsfix
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linklogsfix
  namespace: linklogsfix
  labels:
    k8s-app: linklogsfix
spec:
  selector:
    matchLabels:
      name: linklogsfix
  template:
    metadata:
      labels:
        name: linklogsfix
    spec:
      serviceAccountName: linklogsfix
      containers:
        - name: linklogsfix
          image: quay.io/pbertera/ocp3-linklogsfix
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: DRY_RUN
              value: "yes"
            - name: VERBOSE
              value: "yes"
          volumeMounts:
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            - name: varlogcontainers
              mountPath: /var/log/containers
            - name: varlogpods
              mountPath: /var/log/pods
      volumes:
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: DirectoryOrCreate
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
            type: DirectoryOrCreate
        - name: varlogpods
          hostPath:
            path: /var/log/pods
            type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
